# Copy this file into your repo at .github/workflows/secrets-scan.yml
name: Secret Scanning

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  secrets:
    name: Secret Scanning
    uses: SilentHeroes/.github/.github/workflows/secrets-scan.yml@main
    secrets:
      GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
